#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

version: 2
jobs:
  build:
    docker:
      - image: newtonsystems/tools-docker-grpc-tools:0.2.0
    working_directory: ~/protos
    steps:
      - checkout

      - run:
          name: Run basic check of protos by running compile tool
          command: |
            python -m grpc_tools.protoc -I .  --python_out=. --grpc_python_out=. *.proto

      - deploy:
          name: Run gRPC types build 
          command: |
            curl -u $CIRCLE_API_TOKEN: -d {} https://circleci.com/api/v1.1/project/github/newtonsystems/grpc_types/tree/$CIRCLE_BRANCH

